<a href="https://colab.research.google.com/github/SankalpaFernando/ml_learning/blob/main/npandtorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch

In [6]:
tensor = torch.rand(4,3)
tensor

tensor([[0.4993, 0.0662, 0.2919],
        [0.7339, 0.7334, 0.4992],
        [0.3762, 0.1531, 0.9815],
        [0.4337, 0.7043, 0.8187]])

In [7]:
type(tensor)

torch.Tensor

In [9]:
# Tensor to Numpy
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.49929905, 0.06622946, 0.29192978],
       [0.7339363 , 0.7334206 , 0.49924642],
       [0.37624806, 0.15308523, 0.98149645],
       [0.433735  , 0.7043179 , 0.81866753]], dtype=float32)

In [11]:
numpy_array = np.array([[1,3,2,3],[5,6,7,3]])
numpy_array

array([[1, 3, 2, 3],
       [5, 6, 7, 3]])

In [13]:
# Numpy to Tensor
tensor = torch.from_numpy(numpy_array)
tensor

tensor([[1, 3, 2, 3],
        [5, 6, 7, 3]])

In [14]:
# Even Once converted both share the memory, thus doing any changes on one, will reflect on other

In [15]:
# To create a tensor without sharing memory only values
tensor_copy = torch.tensor(numpy_array)
tensor_copy

tensor([[1, 3, 2, 3],
        [5, 6, 7, 3]])

In [3]:
torch.cuda.is_available()

True

In [4]:
t1 = torch.Tensor([1,2,3])

In [5]:
t1.cuda()

tensor([1., 2., 3.], device='cuda:0')