<a href="https://colab.research.google.com/github/SankalpaFernando/ml_learning/blob/main/pytorch_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch

In [ ]:
import torch

print(torch.__version__)

2.10.0+cpu


In [ ]:
torch.get_default_dtype()

torch.float32

In [ ]:
torch.set_default_dtype(torch.float64)

In [ ]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
#Uninstiallized Tensors with shape of 2 x 2
uninitiated = torch.Tensor(2,2)
uninitiated

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
#Tensor with random data with shape of 2 x 2
random_data=torch.rand(2,2)
random_data

tensor([[0.0891, 0.6407],
        [0.7410, 0.6309]])

In [ ]:
#Tensor filled with a specific value
filled_with_five = torch.full((2,3), fill_value=5)
filled_with_five

tensor([[5, 5, 5],
        [5, 5, 5]])

In [ ]:
#Tensor with square matrix (5x5) where all the elements in diagonal axis are ones
diagonal = torch.eye(5)
diagonal

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#Get all the position of a tensor where values are not zero
torch.nonzero(diagonal)

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [ ]:
initial_tensor = torch.rand(2,3)

In [ ]:
# Any tensor function that has '_' as its suffix performs its operation in place, ie; it does the change within the data unit not by creating a copy
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [ ]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [ ]:
# Out place operation
add_tensor = initial_tensor.add(5)
add_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [ ]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [ ]:
initial_tensor.add_(5)

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [ ]:
initial_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [ ]:
initial_tensor.sqrt_()

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [41]:
x = torch.rand(2,4)
x

tensor([[0.4846, 0.1907, 0.1985, 0.5623],
        [0.5375, 0.0341, 0.9951, 0.2378]])

In [43]:
# Dividing the tensor into parts , param: 1) the tensor 2) the number of parts/chunks needed 3) the dimesion the chunking needs to happen
chunked = torch.chunk(x,2,1)

In [45]:
chunked[0]

tensor([[0.4846, 0.1907],
        [0.5375, 0.0341]])

In [51]:
torch.cat([chunked[0],chunked[1]],1)

tensor([[0.4846, 0.1907, 0.1985, 0.5623],
        [0.5375, 0.0341, 0.9951, 0.2378]])

In [54]:
#Elemnetwise access
random_tensor = torch.rand(2,3)
random_tensor[0,1]

tensor(0.5219)

In [55]:
random_tensor.size()

torch.Size([2, 3])

In [56]:
# Adding an additional Dimension to the tensor
unsqueezed_tensor=random_tensor.unsqueeze(2)

In [57]:
unsqueezed_tensor

tensor([[[0.8221],
         [0.5219],
         [0.4010]],

        [[0.6237],
         [0.0735],
         [0.7027]]])

In [58]:
unsqueezed_tensor.size()

torch.Size([2, 3, 1])

In [60]:
tensor = torch.rand(2,3)
tensor

tensor([[0.9233, 0.2832, 0.9310],
        [0.2684, 0.9505, 0.7690]])

In [64]:
transposed = tensor.transpose(0,1)
transposed

tensor([[0.9233, 0.2684],
        [0.2832, 0.9505],
        [0.9310, 0.7690]])

In [66]:
#Sorting, if the dimension is not specified it sorted by the last dimension
print(tensor)
sorted_tensor,sorted_indices = tensor.sort()
print(sorted_tensor)

tensor([[0.9233, 0.2832, 0.9310],
        [0.2684, 0.9505, 0.7690]])
tensor([[0.2832, 0.9233, 0.9310],
        [0.2684, 0.7690, 0.9505]])


In [70]:
# Absolute value conversion
tensor1 = torch.Tensor([[1,-2,3],[-3,-4,1]])
tensor2 = torch.Tensor([[3,4,-2],[0,3,4]])

In [71]:
tensor1.abs_()

tensor([[1., 2., 3.],
        [3., 4., 1.]])

In [72]:
tensor2.abs_()

tensor([[3., 4., 2.],
        [0., 3., 4.]])

In [74]:
# Matrix Addition
add_matrix = tensor1 + tensor2
add_matrix

tensor([[4., 6., 5.],
        [3., 7., 5.]])

In [75]:
add_matrix = torch.add(tensor1,tensor2)
add_matrix

tensor([[4., 6., 5.],
        [3., 7., 5.]])

In [79]:
# Elementwise Divison
div_matrix = torch.div(tensor1,tensor1+0.3) # dividing each element in the tensor by the value itself + 0.3
div_matrix

tensor([[0.7692, 0.8696, 0.9091],
        [0.9091, 0.9302, 0.7692]])

In [81]:
#Elementwise Multiplication
mul_matrix = torch.mul(tensor1,tensor1)
mul_matrix

tensor([[ 1.,  4.,  9.],
        [ 9., 16.,  1.]])

In [85]:
#Clamp Operation - used to clamp the tensor values between a max and a min value
print(tensor1)
tensor1.clamp(min=0,max=2)

tensor([[1., 2., 3.],
        [3., 4., 1.]])


tensor([[1., 2., 2.],
        [2., 2., 1.]])

In [89]:
# Dot Product
t1 = torch.Tensor([2,3,4])
t2 = torch.Tensor([3,4,1])

torch.dot(t1,t2)

tensor(22.)

In [91]:
# Multiply different dimensions

matrix = torch.Tensor([[1,2,3],[3,4,5]])
vector = torch.Tensor([1,2,2])

torch.mv(matrix,vector)

tensor([11., 21.])

In [92]:
# Matrix Multiplication

t1 = torch.Tensor([[1,2,3],[3,4,5]]) # 2 x 3
t2 = torch.Tensor([[1,2],[3,4],[5,6]]) # 3 x 2

torch.mm(t1,t2)

tensor([[22., 28.],
        [40., 52.]])

In [95]:
# Finding the largest dimension in a particular dimension
torch.argmax(t1,dim=1)

tensor([2, 2])

In [97]:
torch.argmin(t1,dim=1)

tensor([0, 0])